### ISSUE TITLE
waitForElement not waiting as expected in second test case

### ISSUE THREAD

**Issue by devboell** [kentcdodds/react-testing-library#232]
- `react-testing-library` version: ^5.3.0
- `react` version: ^16.6.3
- `node` version: v11.1.0
- `npm` (or `yarn`) version: 6.4.1

### Relevant code or config:

*app.test.js*
```js
import React from 'react'
import { render, waitForElement, wait } from 'react-testing-library'
import { createStore, applyMiddleware } from 'redux'
import thunk from 'redux-thunk'
import { Provider } from 'react-redux'

import reducer from './reducer'
import App from './App'


beforeEach(()=> {
  fetch
    .once(JSON.stringify({ data: 'first text' }))
    .once(JSON.stringify({ data: 'second text' }))
})

afterEach(() =>{
  fetch.resetMocks()
})

const store = createStore(
  reducer,
  applyMiddleware(thunk),
)

const TestComponent = (
  <Provider store={store}>
    <App />
  </Provider>
)

it('should make two async calls', async () => {
  const { container, getByText } = render(TestComponent)
  await waitForElement(() => getByText('texts loaded'))
  // await wait(() => expect(fetch).toHaveBeenCalledTimes(2))
  expect(container.firstChild).toMatchSnapshot()
  expect(fetch).toHaveBeenCalledTimes(2);
})

it('should make two async calls again', async () => {
  const { container, getByText } = render(TestComponent)
  await waitForElement(() => getByText('texts loaded'))
  // await wait(() => expect(fetch).toHaveBeenCalledTimes(2))
  expect(container.firstChild).toMatchSnapshot()
  expect(fetch).toHaveBeenCalledTimes(2);
})
```

*reducer.js*
```js
const initialState = { text: null, otherText: null }

export const setText = text => ({
  type: 'SET_TEXT',
  text,
})

export const setOtherText = text => ({
  type: 'SET_OTHER_TEXT',
  text,
})

export const fetchText = () =>
  async dispatch => {
    const response1 = await fetch('https://loripsum.net/api/1/short')
    const json1 = await response1.json()
    dispatch(setText(json1.data))

    const response2 = await fetch('https://loripsum.net/api/1/short')
    const json2 = await response2.json()
    dispatch(setOtherText(json2.data))
  }


export default (state = initialState, action) => {
  switch (action.type) {
    case 'SET_TEXT': return { ...state, text: action.text }
    case 'SET_OTHER_TEXT': return { ...state, otherText: action.text }
    default: return state
  }
}
```

App.js
```js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { render } from 'react-testing-library';

import{ fetchText } from './reducer'

class App extends Component {
  componentDidMount() {
    this.props.onFetchText()
  }

  render() {
    const { text, otherText } = this.props

    return (
      <div>
        {(text !== null && otherText !== null)
          ? <div>
              <div>{text}</div>
              <div>{otherText}</div>
              <div>texts loaded</div>
            </div>
          : <div>no text</div>
        }
      </div>
    )
  }
}

const mapStateToProps = state =>({
  text: state.text,
  otherText: state.otherText,
})

const mapDispatchToProps = dispatch =>({
  onFetchText: () => dispatch(fetchText()),
})

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(App)
```

setupJest.js

```js
global.fetch = require('jest-fetch-mock')
```

### What you did:
  I am making two async fetch calls in a thunk. In the test I mock them, and in each test case I use waitForElement to wait for an element that is only shown after both fetches are completed 

### What happened:
  In the first test case waitForElement, waits properly for both async calls, but in the second case it doesn't wait.
  In other words, in the first case `expect(fetch).toHaveBeenCalledTimes(2)` passes, and in the second it fails with:

```
./app.test.js
  ● should make two async calls again

    expect(jest.fn()).toHaveBeenCalledTimes(2)

    Expected mock function to have been called two times, but it was called one time.

      43 |   // await wait(() => expect(fetch).toHaveBeenCalledTimes(2))
      44 |   expect(container.firstChild).toMatchSnapshot()
    > 45 |   expect(fetch).toHaveBeenCalledTimes(2);
         |                 ^
      46 | })
      47 |

      at Object.toHaveBeenCalledTimes (app.test.js:45:17)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (app.test.js:19:103)
      at _next (app.test.js:21:194)

```

### Reproduction:

Please let me know if the code above is insufficient and I'll make a repo.

### Problem description:
  In a nutshell, I want each test case to be the same. This example is heavily simplified from my actual project. In each test case I want to simulate different user clicks and then assert what's on the page, and be sure those clicks are done after all the api data is loaded.

### Suggested solution:
A workaround could be to use
`await wait(() => expect(fetch).toHaveBeenCalledTimes(2))`

**Comment by devboell** [comment]
I noticed that both snapshots contain the full data, so I thought it's because the data is in the redux store. So it would make sense that waitForElement is skipped because `<div>texts loaded</div>` is already showing.

I changed the beforeEach in my test file:
```js
let TestComponent

beforeEach(()=> {
  fetch
    .once(JSON.stringify({ data: 'first text' }))
    .once(JSON.stringify({ data: 'second text' }))
  
  const store = createStore(
    reducer,
    applyMiddleware(thunk),
  )
  
  TestComponent = (
    <Provider store={store}>
      <App />
    </Provider>
  )
})
```
Now the second snapshot shows `<div>no text</div>` as expected, but still it seems waitForElement is skipped, and the second test fails with the same output.

**Comment by devboell** [comment]
right, sorry for the bother!
adding:
`import 'react-testing-library/cleanup-after-each';`
made both tests pass.

feel free to delete the issue
