### ISSUE TITLE
test fails at unrelated components

### ISSUE THREAD

**Issue by leogoesger** [kentcdodds/react-testing-library#333]
- `react-testing-library` version: latest
- `react` version: 16.8
- `node` version: 10
- `npm` (or `yarn`) version:

### What you did:

I am not really sure if this is a bug, or simply not understanding the inner works of the library. I have been running into similar problems for a while. Basically, I am testing one component, then usually it fails the test for some completely unrelated components. 

When looking through the traceback, you can see the bug is always generated many level above and circle around some other components that I didn't provide a `mock` with. Is this by design? What is the best approach to solving problems like this?

```
 at Object.get [as ActionDialogsHOC] (src/components/index.ts:189:20)
      at Object.<anonymous> (src/screens/cook/restaurant/create/submit-button/submit-button.tsx:70:23)
      at Object.<anonymous> (src/screens/cook/restaurant/create/submit-button/index.ts:1:1)
      at Object.<anonymous> (src/screens/cook/restaurant/create/form.tsx:9:1)
      at Object.<anonymous> (src/screens/cook/restaurant/create/layout.tsx:4:1)
      at Object.<anonymous> (src/screens/cook/restaurant/create/container.tsx:7:1)
      at Object.<anonymous> (src/screens/cook/restaurant/api/index.ts:14:1)
      at Object.<anonymous> (src/screens/home/sections/subscribe.tsx:13:1)
      at Object.<anonymous> (src/screens/home/sections/index.ts:3:1)
      at Object.<anonymous> (src/screens/home/layout.tsx:4:1)
      at Object.<anonymous> (src/screens/home/container.tsx:2:1)
      at Object.<anonymous> (src/screens/routes.tsx:13:1)
      at Object.<anonymous> (src/App.tsx:9:1)
      at Object.<anonymous> (src/components/reserved-events-card/card-body.tsx:11:1)
      at Object.<anonymous> (src/components/reserved-events-card/card-content.tsx:3:1)
      at Object.<anonymous> (src/components/reserved-events-card/layout.tsx:6:1)
      at Object.<anonymous> (src/components/reserved-events-card/container.tsx:4:1)
      at Object.<anonymous> (src/components/reserved-events-card/index.ts:1:1)
      at Object.<anonymous> (src/components/index.ts:12:1)
      at Object.<anonymous> (src/screens/cook/summary/incomplete-events/incomplete-table.tsx:6:1)
      at Object.<anonymous> (src/screens/cook/summary/incomplete-events/index.ts:7:1)
      at Object.<anonymous> (src/screens/cook/summary/layout.tsx:6:1)
      at Object.<anonymous> (src/screens/cook/summary/container.tsx:4:1)
      at Object.<anonymous> (src/screens/cook/summary/__tests__/summary.container.test.tsx:8:1)
```

You can see the test componet is actually `summary.container`, but it fails all the way back up to my entry file `App`.

Thanks for any help!

**Comment by kentcdodds** [comment]
Hi @leogoesger,

My guess is that code in the App is being imported through several layers of code imports. Really hard to tell from here though, sorry. 😬 Good luck.

**Comment by leogoesger** [comment]
@kentcdodds that's it! thanks! Took me hours, it is weird once you have things imported from a file, and then it keeps going deeper and deeper into that file...
