### ISSUE TITLE
React lazy and suspense component not loading

### ISSUE THREAD

**Issue by GnanaAjana** [kentcdodds/react-testing-library#352]
Am trying to load a component using react suspense and load.

In async.js

````
function lazyWithPreload(factory) {
  const component = React.lazy(factory);
  component.preload = factory;
  return component;
}`

`const AsyncComponent = lazyWithPreload(() =>
  import(/* webpackChunkName: "Test form" */ 'components/Test')
);
````

In component.js,

````
<Suspense fallback={Loader()}>
            <AsyncTest data-testid="test-form" {...this.props} />
</Suspense>
````

In the test case,

````
test('chatwindow with home page', async () => {
    const { getByTestId, container, queryByTestId } = render(
      <Suspense fallback={<div />}>
        <Component />
      </Suspense>
    );

    expect(container.firstChild).toMatchSnapshot();
    await waitForElement(() => queryByTestId('test-form'));
    expect(queryByTestId('test-form')).toBeTruthy();
  });
````

I got the error as,

`require.ensure is not a function`.

So I implemented in async.js as 

````
if (process.env.NODE_ENV === 'test') {
  require.ensure = (deps, cb) => {
    return cb(require);
  };
}
````

In the snapshot, component gets loaded but getting error as 
`Timed out in waitForElement.`

Version:
"react-testing-library" : "^5.1.0"
"React": "^16.8.3"

I got reference from this
"https://github.com/facebook/create-react-app/issues/1064"

let me know if I need to change anything in this. or ask me for any further details to resolve this?

**Comment by kentcdodds** [comment]
Hi @GnanaAjana, I think you need this: https://github.com/airbnb/babel-plugin-dynamic-import-node

Good luck!

**Comment by jaydeep987** [comment]
@kentcdodds  I have this setup:
```
// routes.tsx

async function loadModule(loadingFactory: () => Promise<any>, moduleName: string): Promise<{default: any}> {
  try {
    return {
      default: (await loadingFactory())[moduleName],
    };
  } catch (err) {
    console.log(err);
    return {
      default: () => <div><RouteError errorText={err.message} /></div>,
    };
  }
}

const EmployeeManagement = React.lazy(
  () => loadModule(() => import('~pages/employee-management/employee-management'), 'EmployeeManagement'),
);
```

And in test it gives error:
```
Error: Not supported
        at /src/pages/routes/routes.tsx:26:26
        at loadingFactory (/src/pages/routes/routes.tsx:15:23)
```

In test I used `React.Suspense` too!
Using `react@^16.8.3`, `@testing-library/react@^8.0.1`.
